version: '3'
services:
  nestjs:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: hogogo
      POSTGRES_PASSWORD: hogogo2012
      POSTGRES_DB: volunteer_management
    ports:
      - '5432:5432'